#! /bin/bash

for alpha1 in $(seq 5.1 0.1 5.1); do
    for alpha2 in $(seq 6.6 10 6.6); do
        echo -n "Alpha1: $alpha1, Alpha2: $alpha2: "
        scripts/run_vad.sh $alpha1 $alpha2 | grep TOTAL
    done
done
